### ISSUE TITLE
Licensing problems with your repo

### ISSUE THREAD

**Issue by freemin7** [thethoughtemporium/Whose-gene-is-it-anyway#1]
> These plasmids are released as creative commons fair use. You may download them, modify them, even have them synthesized if you so choose. The only requirement is that you give attribution to The Thought Emporium and whoever was helping to design the plasmid during the stream.

Seems to approximate a license. However there are several it has several problems:
- "creative commons fair use" is undefined since there is no license with that name. Fair use is a USA specific legal concept which does not exist in different jurisdictions.
- There are several creative commons licenses which one is used matters.
- Would you be allowed to synthesize them yourself?
- How would attribution look like? Including your name in the plasmid? For software it is trivial since the length of a license is minimal compared to the code/binary. However for DNA this is not the case.
- In software it is usually seen as the maintainers task to maintain the list of all people who have contributed to the project. "whoever was helping to design the plasmid during the stream" is woefully undefined. Would you include the one who pointed you the base plasmid? The other people who pointed you plasmids who did not work? The guy who made the GNU/Milk joke? Would screen name on Youtube suffice or would researching there real identity be necessary? What if the stream or the chat log gets lost? I think under those circumstances it is impossible to reuse your work, which is not what you intend. Also it think it might be required to watch all your videos since there is currently no mapping between videos and plasmids. 
- I am not sure if plasmids designs when handed out for free for come with implied guarantees in some jurisdictions. Software licenses almost always include boilerplates stating that the software is provided as is and without any warranties. Maybe if you should choose a license which includes such a disclaimer.

I am not very familiar with open source plasmid licenses however it seems that the scene is not very developed so choosing a (slightly modified) software license might be the way to go.

I could help you pick a license if you feel not comfortable to do that on your own.

**Comment by adriaan1313** [comment]
> an USA specific legal concept 

'USA' begins with a U which is pronounced as /ˈjuː/ thus 'an' should be 'a'.

**Comment by freemin7** [comment]
@adriaan1313 Thanks for pointing that. It never ceases to amaze me how broken the English language is.

**Comment by l33tLumberjack** [comment]
The full text for CC BY-SA 4.0 can be found here https://choosealicense.com/licenses/cc-by-sa-4.0/

**Comment by freemin7** [comment]
@l33tLumberjack I updated my issue. When i issued it which CC license was choosen was not clear.
