### ISSUE TITLE
Zombie Serum LacZ Alpha missing stop codon?

### ISSUE THREAD

**Issue by CarlKenner** [thethoughtemporium/Whose-gene-is-it-anyway#20]
Disclaimer: I haven't studied biology, and I'm completely new to this.

LacZ Alpha appears to be missing a stop codon. EDIT: Specifically at 4795, I would have expected an R followed by a stop codon. Instead, f1 ori starts immediately at 4795 without anything separating it from the end of LacZ Alpha.

The definitely not zombie serum contains LacZ Alpha, except something (AAV packaging surrounding code to produce your cancer-tagging protein and to protect itself in a human cell) has already been inserted near the start of it, breaking it, which I assume was deliberate.

But if you're planning on putting this into cells that lack LacZ Alpha, then removing everything from pacI to pacI using restriction enzymes and then using blue/white screening to make the cells that have had the code successfully removed turn blue, then the missing stop codon might be a problem. (Or it might not, I have no experience with this.)

**Comment by the-thought-emporium** [comment]
Where.... are you looking? I'm looking at v3 and there's no lacz in there at all.

**Comment by CarlKenner** [comment]
Just because it isn't labelled doesn't mean it isn't there.

See the last two commits of my pull request to see what I changed, or open the malaria cancer therapy/finished plasmids/Definitely not zombie serum v3.1 aav IgGA.gb to see the final result. I improved the labelling slightly, so you can now see where lacZ alpha is. And I added an R and a stop codon, because the extra R on the end seems to be the most common than not having it.

Again, I'm not a biologist, and this is the first time I've ever done genetic engineering or touched any of this stuff, so I may be screwing things up terribly, lol. Don't assume my changes aren't going to catastrophically break something.
