### ISSUE TITLE
Silk project lacking resources

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [thethoughtemporium/Whose-gene-is-it-anyway#23]
Would it be possible to upload your Google Doc containing some of the DNA sequences you used for the randomization step? If you don't mind, I'd like to write a little genetic randomizer program for you since I'm sure you'll be working on other versions of the silk project to get different properties.

Don't have money to donate but I do have programming ability and free time.

**Comment by the-thought-emporium** [comment]
We've already built such a thing: https://thethoughtemporium.github.io/Whose-gene-is-it-anyway/scripts/codonscromble/codonscromble.html?fbclid=IwAR2yLZSMDvLkts6qqMCqz6BC3r0ZKosY-Gu1IA9Pgc9GlqwkzYkrsWMgYJg

**Comment by Adrian-at-CrimsonAuzre** [comment]
Oh cool, must have missed that stream.
