### ISSUE TITLE
Cancer immunotherapy might cause allergies against placenta

### ISSUE THREAD

**Issue by Robotic-Brain** [thethoughtemporium/Whose-gene-is-it-anyway#7]
I'm not a Biologist, just a curious laymen so take the following with a grain of salt.

If I understand the concept of the "malaria cancer therapy" project correctly it basically tries to make your immune system react to cancer cells with a normal immune reaction.
The marker you're using however is the same as expressed in human placenta cells.

Wont this "treatment" then basically make your immune system also permanently react against your placenta (if you have one).
So in effect people treated with this would develop an allergy against their own placenta, rendering them infertile?

If this reasoning holds this type of immunotherapy would be an incredibly stupid idea...

**Comment by Constant-ine** [comment]
To my understanding, the lentivirus will inject itself to cells and replicate the malarial protein (rVar2) carrying the toxin that will eat up the cancer cells, these will indeed stick to glycosoaminoglycans that are found in cancer cells and the placenta so it makes sense that you don't want to inject this to someone pregnant, however the virus itself will clear up after a while so I don't see how it'd cause a permanent 'allergic' reaction. The rate of cancer cells killed and how long will it take for the virus to clear up from the body will be unknown until we have some concrete tests done.

**Comment by chironexiru** [comment]
Couple things. First, if you've got cancer, you've got bigger problems than placenta. Primarily, you'd be dead before you could give birth and I'd rather be alive than pregnant. But this is also just an initial version. It's possible to add a kill switch to later versions that kill off any cells carrying the gene, and therefor the malarial protein will clear from the patients system quickly once it's done it's job. Or do the reverse and have it only run when you take a specific compound, and as soon as you stop the gene turns off. But even as it stands this should only last a couple weeks. There's nothing in the construct to make this gene last so it should get cleared out on it's own in about 2 weeks
